[build]
  publish = "dist"
  command = "npm run build"

[plugins]
  [[plugins]]
    package = "@netlify/plugin-cache-nextjs"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefer-offline --no-audit"
